name: light8
channels:
  - conda-forge
  - defaults
  - pip:
    - absl-py==0.13.0
    - aiohttp==3.7.4.post0
    - async-timeout==3.0.1
    - attrs==21.2.0
    - cachetools==4.2.2
    - chardet==4.0.0
    - charset-normalizer==2.0.4
    - cycler==0.10.0
    - dataclasses==0.6
    - elasticdeform==0.4.9
    - fsspec==2021.7.0
    - future==0.18.2
    - google-auth==1.34.0
    - google-auth-oauthlib==0.4.5
    - grpcio==1.39.0
    - h5py==3.3.0
    - idna==3.2
    - imageio==2.9.0
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - markdown==3.3.4
    - matplotlib==3.4.2
    - monai==0.7.0
    - multidict==5.1.0
    - networkx==2.6.2
    - numpy==1.21.1
    - oauthlib==3.1.1
    - opencv-python==4.5.3.56
    - packaging==21.0
    - pandas==1.3.1
    - pillow==8.3.1
    - protobuf==3.17.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.1
    - pydicom==2.2.2
    - pynrrd==0.4.2
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pytorch-lightning==1.5.8
    - pytz==2021.1
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - rt-utils==1.1.6
    - scikit-image==0.18.2
    - scikit-learn==0.24.2
    - scipy==1.7.1
    - simpleitk==2.1.1
    - six==1.16.0
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - threadpoolctl==2.2.0
    - tifffile==2021.8.8
    - torch==1.10.1
    - torchmetrics==0.5.0
    - tqdm==4.62.0
    - typing-extensions==4.0.1
    - umap==0.1.1
    - urllib3==1.26.6
    - werkzeug==2.0.1
    - yarl==1.6.3
