OralCavity: OralCavity.*
Larynx: Larynx.*
Nrv_Optic_L: Nrv_Optic_L.*
Parotid_L: Parotid_L.*
Esophagus: Esophagus.*
Glnd_Submand_R: Glnd_Submand_R.*
Glnd_Lacrimal_R: Glnd_Lacrimal_R.*
Cochlea_R: Cochlea_R.*
BrachialPlex_R: BrachialPlex_R.*
Glnd_Submand_L: Glnd_Submand_L.*
SpinalCord: SpinalCord.*
Cochlea_L: Cochlea_L.*
Lens_L: Lens_L.*
Brain: Brain.*
Musc_Constrict_S: Musc_Constrict_S.*
GTVn: GTVn_*
Musc_Constrict_M: Musc_Constrict_M.*
Nrv_Optic_R: Nrv_Optic_R.*
Lens_R: Lens_R.*
Glnd_Lacrimal_L: Glnd_Lacrimal_L.*
Parotid_R: Parotid_R.*
OpticChiasm: OpticChiasm.*
Mandible_Bone: Mandible_Bone.*
Musc_Constrict_I: Musc_Constrict_I.*
Eye_L: Eye_L.*
Brainstem: Brainstem.*
Lips: Lips.*
Eye_R: Eye_R.*
BrachialPlex_L: BrachialPlex_L.*
GTVp: GTVp.*
EXTERNAL: EXTERNAL.*